name: build bworks homepage
run-name: ${{ github.actor }} is building bworks homepage 🚀
on:
 workflow_dispatch:
# Some objects are defined but never used lead to warnings when build
# Treating warnings as errors because process.env.CI = true ==> step build api exit code 1 and fail
# temporary fix by set process.env.CI = false
env:
  CI: false
jobs:
  build-push-docker-image:
    runs-on: ubuntu-latest
    environment:
      name: mainnet
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Generate .env file for homepage
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_NEXT_PUBLIC_API_URL: ${{ vars.NEXT_PUBLIC_API_URL }}
          envkey_NEXT_PUBLIC_CONTRACT_TXS: ${{ vars.NEXT_PUBLIC_CONTRACT_TXS }}
          envkey_NEXT_PUBLIC_TOKEN_EXPIRE: ${{ vars.NEXT_PUBLIC_TOKEN_EXPIRE }}
          envkey_NEXT_PUBLIC_JWT_HOME_PAGE_TOKEN_SECRET: ${{ secrets.NEXT_PUBLIC_JWT_HOME_PAGE_TOKEN_SECRET }}
          directory: .
          file_name: .env
          fail_on_empty: false
      #- name: echo .env file
      #  run: |
      #    echo "cat .env"
      #    cat .env
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: 121427815363.dkr.ecr.ap-southeast-1.amazonaws.com/bworks
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          #username: ${{ secrets.DOCKERHUB_USERNAME }}
          #password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ vars.BWORKS_HOMEPAGE_TAG }}
          #tags: 121427815363.dkr.ecr.ap-southeast-1.amazonaws.com/bworks:frontend-testnet
          #tags: jackchuong/itl:bworks-frontend-testnet
          context: .
          file: ./docker-configs/Dockerfile
      - run: echo "🍏 This job's status is ${{ job.status }}."
